model: vit
outputpath: experiments/vit/30k_best

dataset_base_path: data/flickr30k
vocab_path: utils/vocab_set30k.pkl
image_len: 224
embedding_dim: 300
attention_dim: 256
decoder_size: 256
sample_method: greed # 'greed' or 'beam'
train_args:
    batch_size: 128
    learning_rate: !!float 1e-3
    num_epochs: 30
    save_freq: 10
    # --- Scheduled Sampling Parameters ---
    scheduled_sampling_on: False      # 不使用 Scheduled Sampling 
    ss_type: 'linear'
    ss_start_prob: 1.0                # 训练开始时的 teacher forcing 概率
    ss_end_prob: 0.2                  # 训练结束时的 teacher forcing 概率
eval_args:
    batch_size: 1

test_model_path: ckpt/vit30k.pt
test_result_path: results/vit30k